
package com.infor.businessinterface.item_val;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Item_VALService", targetNamespace = "http://www.infor.com/businessinterface/Item_VAL", wsdlLocation = "https://eaibt.valmet.com:7843/EAI/Item_VAL/Rx/processItemData?wsdl")
public class ItemVALService
    extends Service
{

    private final static URL ITEMVALSERVICE_WSDL_LOCATION;
    private final static WebServiceException ITEMVALSERVICE_EXCEPTION;
    private final static QName ITEMVALSERVICE_QNAME = new QName("http://www.infor.com/businessinterface/Item_VAL", "Item_VALService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://eaibt.valmet.com:7843/EAI/Item_VAL/Rx/processItemData?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ITEMVALSERVICE_WSDL_LOCATION = url;
        ITEMVALSERVICE_EXCEPTION = e;
    }

    public ItemVALService() {
        super(__getWsdlLocation(), ITEMVALSERVICE_QNAME);
    }

    public ItemVALService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ITEMVALSERVICE_QNAME, features);
    }

    public ItemVALService(URL wsdlLocation) {
        super(wsdlLocation, ITEMVALSERVICE_QNAME);
    }

    public ItemVALService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ITEMVALSERVICE_QNAME, features);
    }

    public ItemVALService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ItemVALService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ItemVAL
     */
    @WebEndpoint(name = "Item_VALSoapPort")
    public ItemVAL getItemVALSoapPort() {
        return super.getPort(new QName("http://www.infor.com/businessinterface/Item_VAL", "Item_VALSoapPort"), ItemVAL.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ItemVAL
     */
    @WebEndpoint(name = "Item_VALSoapPort")
    public ItemVAL getItemVALSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.infor.com/businessinterface/Item_VAL", "Item_VALSoapPort"), ItemVAL.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ITEMVALSERVICE_EXCEPTION!= null) {
            throw ITEMVALSERVICE_EXCEPTION;
        }
        return ITEMVALSERVICE_WSDL_LOCATION;
    }

}
