
package com.infor.businessinterface.item_val;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Item_VAL", targetNamespace = "http://www.infor.com/businessinterface/Item_VAL")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ItemVAL {


    /**
     * 
     * @param processItemDataRequest
     * @return
     *     returns com.infor.businessinterface.item_val.ProcessItemDataResponseType
     * @throws Result
     */
    @WebMethod
    @WebResult(name = "processItemDataResponse", partName = "processItemDataResponse")
    public ProcessItemDataResponseType processItemData(
        @WebParam(name = "processItemDataRequest", partName = "processItemDataRequest")
        ProcessItemDataRequestType processItemDataRequest)
        throws Result
    ;

}
