
package com.infor.businessinterface.disassemblylines_val;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DisAssemblyLines_VAL", targetNamespace = "http://www.infor.com/businessinterface/DisAssemblyLines_VAL")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DisAssemblyLinesVAL {


    /**
     * 
     * @param processDisAssemblyLinesRequest
     * @return
     *     returns com.infor.businessinterface.disassemblylines_val.ProcessDisAssemblyLinesResponseType
     * @throws Result
     */
    @WebMethod
    @WebResult(name = "processDisAssemblyLinesResponse", partName = "processDisAssemblyLinesResponse")
    public ProcessDisAssemblyLinesResponseType processDisAssemblyLines(
        @WebParam(name = "processDisAssemblyLinesRequest", partName = "processDisAssemblyLinesRequest")
        ProcessDisAssemblyLinesRequestType processDisAssemblyLinesRequest)
        throws Result
    ;

}
