
package com.infor.businessinterface.disassemblylines_val;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DisAssemblyLines_VALService", targetNamespace = "http://www.infor.com/businessinterface/DisAssemblyLines_VAL", wsdlLocation = "https://eaibt.valmet.com:7843/EAI/DisassemblyLines/processDisAssemblyLinesRequest?wsdl")
public class DisAssemblyLinesVALService
    extends Service
{

    private final static URL DISASSEMBLYLINESVALSERVICE_WSDL_LOCATION;
    private final static WebServiceException DISASSEMBLYLINESVALSERVICE_EXCEPTION;
    private final static QName DISASSEMBLYLINESVALSERVICE_QNAME = new QName("http://www.infor.com/businessinterface/DisAssemblyLines_VAL", "DisAssemblyLines_VALService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://eaibt.valmet.com:7843/EAI/DisassemblyLines/processDisAssemblyLinesRequest?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DISASSEMBLYLINESVALSERVICE_WSDL_LOCATION = url;
        DISASSEMBLYLINESVALSERVICE_EXCEPTION = e;
    }

    public DisAssemblyLinesVALService() {
        super(__getWsdlLocation(), DISASSEMBLYLINESVALSERVICE_QNAME);
    }

    public DisAssemblyLinesVALService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DISASSEMBLYLINESVALSERVICE_QNAME, features);
    }

    public DisAssemblyLinesVALService(URL wsdlLocation) {
        super(wsdlLocation, DISASSEMBLYLINESVALSERVICE_QNAME);
    }

    public DisAssemblyLinesVALService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DISASSEMBLYLINESVALSERVICE_QNAME, features);
    }

    public DisAssemblyLinesVALService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DisAssemblyLinesVALService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DisAssemblyLinesVAL
     */
    @WebEndpoint(name = "DisAssemblyLines_VALSoapPort")
    public DisAssemblyLinesVAL getDisAssemblyLinesVALSoapPort() {
        return super.getPort(new QName("http://www.infor.com/businessinterface/DisAssemblyLines_VAL", "DisAssemblyLines_VALSoapPort"), DisAssemblyLinesVAL.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DisAssemblyLinesVAL
     */
    @WebEndpoint(name = "DisAssemblyLines_VALSoapPort")
    public DisAssemblyLinesVAL getDisAssemblyLinesVALSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.infor.com/businessinterface/DisAssemblyLines_VAL", "DisAssemblyLines_VALSoapPort"), DisAssemblyLinesVAL.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DISASSEMBLYLINESVALSERVICE_EXCEPTION!= null) {
            throw DISASSEMBLYLINESVALSERVICE_EXCEPTION;
        }
        return DISASSEMBLYLINESVALSERVICE_WSDL_LOCATION;
    }

}
