
package com.infor.businessinterface.projectdeliverable_val;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProjectDeliverable_VAL", targetNamespace = "http://www.infor.com/businessinterface/ProjectDeliverable_VAL")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProjectDeliverableVAL {


    /**
     * 
     * @param createProjectDeliverableRequest
     * @return
     *     returns com.infor.businessinterface.projectdeliverable_val.CreateProjectDeliverableResponseType
     * @throws Result
     */
    @WebMethod
    @WebResult(name = "createProjectDeliverableResponse", partName = "createProjectDeliverableResponse")
    public CreateProjectDeliverableResponseType createProjectDeliverable(
        @WebParam(name = "createProjectDeliverableRequest", partName = "createProjectDeliverableRequest")
        CreateProjectDeliverableRequestType createProjectDeliverableRequest)
        throws Result
    ;

}
