
package com.infor.businessinterface.itemcostcalculation_val;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ItemCostCalculation_VALService", targetNamespace = "http://www.infor.com/businessinterface/ItemCostCalculation_VAL", wsdlLocation = "https://v0140a.vstage.co:7843/EAI/ItemCostCalculation_VAL?wsdl")
public class ItemCostCalculationVALService
    extends Service
{

    private final static URL ITEMCOSTCALCULATIONVALSERVICE_WSDL_LOCATION;
    private final static WebServiceException ITEMCOSTCALCULATIONVALSERVICE_EXCEPTION;
    private final static QName ITEMCOSTCALCULATIONVALSERVICE_QNAME = new QName("http://www.infor.com/businessinterface/ItemCostCalculation_VAL", "ItemCostCalculation_VALService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://v0140a.vstage.co:7843/EAI/ItemCostCalculation_VAL?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ITEMCOSTCALCULATIONVALSERVICE_WSDL_LOCATION = url;
        ITEMCOSTCALCULATIONVALSERVICE_EXCEPTION = e;
    }

    public ItemCostCalculationVALService() {
        super(__getWsdlLocation(), ITEMCOSTCALCULATIONVALSERVICE_QNAME);
    }

    public ItemCostCalculationVALService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ITEMCOSTCALCULATIONVALSERVICE_QNAME, features);
    }

    public ItemCostCalculationVALService(URL wsdlLocation) {
        super(wsdlLocation, ITEMCOSTCALCULATIONVALSERVICE_QNAME);
    }

    public ItemCostCalculationVALService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ITEMCOSTCALCULATIONVALSERVICE_QNAME, features);
    }

    public ItemCostCalculationVALService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ItemCostCalculationVALService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ItemCostCalculationVAL
     */
    @WebEndpoint(name = "ItemCostCalculation_VALSoapPort")
    public ItemCostCalculationVAL getItemCostCalculationVALSoapPort() {
        return super.getPort(new QName("http://www.infor.com/businessinterface/ItemCostCalculation_VAL", "ItemCostCalculation_VALSoapPort"), ItemCostCalculationVAL.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ItemCostCalculationVAL
     */
    @WebEndpoint(name = "ItemCostCalculation_VALSoapPort")
    public ItemCostCalculationVAL getItemCostCalculationVALSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.infor.com/businessinterface/ItemCostCalculation_VAL", "ItemCostCalculation_VALSoapPort"), ItemCostCalculationVAL.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ITEMCOSTCALCULATIONVALSERVICE_EXCEPTION!= null) {
            throw ITEMCOSTCALCULATIONVALSERVICE_EXCEPTION;
        }
        return ITEMCOSTCALCULATIONVALSERVICE_WSDL_LOCATION;
    }

}
