
package com.infor.businessinterface.billofmaterial_val;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BillOfMaterial_VALService", targetNamespace = "http://www.infor.com/businessinterface/BillOfMaterial_VAL", wsdlLocation = "https://eaibt.valmet.com:7843/EAI/Item_VAL/Rx/processItemBOMData?wsdl")
public class BillOfMaterialVALService
    extends Service
{

    private final static URL BILLOFMATERIALVALSERVICE_WSDL_LOCATION;
    private final static WebServiceException BILLOFMATERIALVALSERVICE_EXCEPTION;
    private final static QName BILLOFMATERIALVALSERVICE_QNAME = new QName("http://www.infor.com/businessinterface/BillOfMaterial_VAL", "BillOfMaterial_VALService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://eaibt.valmet.com:7843/EAI/Item_VAL/Rx/processItemBOMData?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BILLOFMATERIALVALSERVICE_WSDL_LOCATION = url;
        BILLOFMATERIALVALSERVICE_EXCEPTION = e;
    }

    public BillOfMaterialVALService() {
        super(__getWsdlLocation(), BILLOFMATERIALVALSERVICE_QNAME);
    }

    public BillOfMaterialVALService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BILLOFMATERIALVALSERVICE_QNAME, features);
    }

    public BillOfMaterialVALService(URL wsdlLocation) {
        super(wsdlLocation, BILLOFMATERIALVALSERVICE_QNAME);
    }

    public BillOfMaterialVALService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BILLOFMATERIALVALSERVICE_QNAME, features);
    }

    public BillOfMaterialVALService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillOfMaterialVALService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BillOfMaterialVAL
     */
    @WebEndpoint(name = "BillOfMaterial_VALSoapPort")
    public BillOfMaterialVAL getBillOfMaterialVALSoapPort() {
        return super.getPort(new QName("http://www.infor.com/businessinterface/BillOfMaterial_VAL", "BillOfMaterial_VALSoapPort"), BillOfMaterialVAL.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillOfMaterialVAL
     */
    @WebEndpoint(name = "BillOfMaterial_VALSoapPort")
    public BillOfMaterialVAL getBillOfMaterialVALSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.infor.com/businessinterface/BillOfMaterial_VAL", "BillOfMaterial_VALSoapPort"), BillOfMaterialVAL.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BILLOFMATERIALVALSERVICE_EXCEPTION!= null) {
            throw BILLOFMATERIALVALSERVICE_EXCEPTION;
        }
        return BILLOFMATERIALVALSERVICE_WSDL_LOCATION;
    }

}
