
package com.infor.businessinterface.multilevelbomdetails_val;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MultilevelBOMDetails_VALService", targetNamespace = "http://www.infor.com/businessinterface/MultilevelBOMDetails_VAL", wsdlLocation = "https://eaibt.valmet.com:7843/EAI/BOM/MultilevelBOMDetails?wsdl")
public class MultilevelBOMDetailsVALService
    extends Service
{

    private final static URL MULTILEVELBOMDETAILSVALSERVICE_WSDL_LOCATION;
    private final static WebServiceException MULTILEVELBOMDETAILSVALSERVICE_EXCEPTION;
    private final static QName MULTILEVELBOMDETAILSVALSERVICE_QNAME = new QName("http://www.infor.com/businessinterface/MultilevelBOMDetails_VAL", "MultilevelBOMDetails_VALService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://eaibt.valmet.com:7843/EAI/BOM/MultilevelBOMDetails?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MULTILEVELBOMDETAILSVALSERVICE_WSDL_LOCATION = url;
        MULTILEVELBOMDETAILSVALSERVICE_EXCEPTION = e;
    }

    public MultilevelBOMDetailsVALService() {
        super(__getWsdlLocation(), MULTILEVELBOMDETAILSVALSERVICE_QNAME);
    }

    public MultilevelBOMDetailsVALService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MULTILEVELBOMDETAILSVALSERVICE_QNAME, features);
    }

    public MultilevelBOMDetailsVALService(URL wsdlLocation) {
        super(wsdlLocation, MULTILEVELBOMDETAILSVALSERVICE_QNAME);
    }

    public MultilevelBOMDetailsVALService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MULTILEVELBOMDETAILSVALSERVICE_QNAME, features);
    }

    public MultilevelBOMDetailsVALService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MultilevelBOMDetailsVALService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MultilevelBOMDetailsVAL
     */
    @WebEndpoint(name = "MultilevelBOMDetails_VALSoapPort")
    public MultilevelBOMDetailsVAL getMultilevelBOMDetailsVALSoapPort() {
        return super.getPort(new QName("http://www.infor.com/businessinterface/MultilevelBOMDetails_VAL", "MultilevelBOMDetails_VALSoapPort"), MultilevelBOMDetailsVAL.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MultilevelBOMDetailsVAL
     */
    @WebEndpoint(name = "MultilevelBOMDetails_VALSoapPort")
    public MultilevelBOMDetailsVAL getMultilevelBOMDetailsVALSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.infor.com/businessinterface/MultilevelBOMDetails_VAL", "MultilevelBOMDetails_VALSoapPort"), MultilevelBOMDetailsVAL.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MULTILEVELBOMDETAILSVALSERVICE_EXCEPTION!= null) {
            throw MULTILEVELBOMDETAILSVALSERVICE_EXCEPTION;
        }
        return MULTILEVELBOMDETAILSVALSERVICE_WSDL_LOCATION;
    }

}
