
package com.infor.businessinterface.multilevelbomdetails_val;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MultilevelBOMDetails_VAL", targetNamespace = "http://www.infor.com/businessinterface/MultilevelBOMDetails_VAL")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MultilevelBOMDetailsVAL {


    /**
     * 
     * @param getBOMDetailsRequest
     * @return
     *     returns com.infor.businessinterface.multilevelbomdetails_val.GetBOMDetailsResponseType
     * @throws Result
     */
    @WebMethod(operationName = "GetBOMDetails")
    @WebResult(name = "GetBOMDetailsResponse", partName = "GetBOMDetailsResponse")
    public GetBOMDetailsResponseType getBOMDetails(
        @WebParam(name = "GetBOMDetailsRequest", partName = "GetBOMDetailsRequest")
        GetBOMDetailsRequestType getBOMDetailsRequest)
        throws Result
    ;

}
